### ISSUE TITLE
Test to see if the incore-lab can access the cluster's internal network

### ISSUE THREAD

**Issue by ywkim312** [IN-CORE/incore-lab#137]
To enable a new DataWolf instance to work within IN-CORE Studio, DataWolf needs access to the internal network of the Kubernetes cluster. This requires PyINCORE to use the internal URLs of the services within the cluster. However, allowing this setup introduces a potential security risk, as it may enable IN-CORE Lab users to access the cluster's internal services. This could lead to security vulnerabilities.

Test whether IN-CORE Lab can access the internal network of the cluster. Additionally, if access is possible, explore ways to block this route to enhance security.

**Comment by ywkim312** [comment]
According to various web searches, it is possible to access the Kubernetes internal network from a JupyterLab instance spawned by JupyterHub in a Kubernetes cluster, provided the networking configuration and policies allow it. 

The key points to consider:

1. Networking Inside the Cluster
JupyterLab runs as a pod within the Kubernetes cluster, so it should be able to communicate with other pods and services in the same namespace or cluster.
Use the Kubernetes DNS service to resolve other services. For example, a service named incore-svc-data in namespace incore can typically be accessed at incore-svc-data.incore.svc.cluster.local.

2. Accessing Cluster Resources
Cluster IP Services: You can directly access ClusterIP services using their DNS names as described above.
Node Ports and Load Balancers: If you need to interact with services exposed via NodePort or LoadBalancer, you might need the external IPs or specific port configurations.

3. Service Account and Role-Based Access Control (RBAC)
If your JupyterLab notebook needs to interact with the Kubernetes API (e.g., to manage pods, fetch resource data), ensure the pod has an appropriate service account with the necessary permissions.

4. Network Policies
If Kubernetes NetworkPolicies are enforced in your cluster, ensure they allow traffic between the JupyterLab pod and the other pods or services it needs to access.

5. Configuring Environment Variables
Certain Kubernetes-related configurations might already be injected into the JupyterLab environment via environment variables like KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT.

6. Debugging Network Access
Use tools like ping, curl, or Python libraries (e.g., requests, kubernetes) within the JupyterLab terminal to test connectivity

**Comment by ywkim312** [comment]
I tested checking numbers 1 and 2, and both of them were unsuccessful, which means that they don't work with those methods.

For number 1
```
http://incore-doc-api.incore.svc.cluster.local:80
```

For number 2, the following command will give the IP 
```
kubectl get svc -n incore incore-svc-data
```

Also, checked with other various way but all of them failed to access the services

**Comment by ywkim312** [comment]
This yaml file does
- Traffic to private IP ranges is blocked.
- Traffic to the public internet is allowed.

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jupyterlab-isolate
  namespace: <namespace>
spec:
  podSelector:
    matchLabels:
      app: jupyterhub
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 192.168.0.0/16
              - 172.16.0.0/12
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
```

**Comment by ywkim312** [comment]
This yaml file use NamespaceSelector to deny access from JupyterLab pods to all pods in a specific namespace.

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-incore-namespace
  namespace: jupyterhub
spec:
  podSelector:
    matchLabels:
      app: jupyterhub
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: incore
```

**Comment by ywkim312** [comment]
This denies all
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-egress
  namespace: incore
spec:
  podSelector:
    matchLabels:
      app: jupyterlab
  policyTypes:
    - Egress
  egress: []
```

**Comment by ywkim312** [comment]
I found that there was a network policy already in there named singleuser NetworkPolicy, and it is fairly restrictive, and here are the key points affecting traffic to incore-svc-data or other internal services:

1 Key Observations from the Policy
- Egress Traffic Rules:
-- Egress is allowed to specific pods and ports:

--- Pods with labels like:
- app=jupyterhub, component=hub
- app=jupyterhub, component=proxy
- app=jupyterhub, component=autohttps
- DNS traffic (port 53/TCP and 53/UDP) to kube-system and private IP ranges (e.g., 10.0.0.0/8).
- Traffic to public IPs (0.0.0.0/0) is allowed, except for:
- Private ranges (10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16).
- Metadata IP (169.254.169.254/32).
- Traffic to incore-svc-data:
- 
- Internal service IPs like 10.42.7.209 fall within the blocked CIDR ranges (10.0.0.0/8), so egress traffic to this service is explicitly denied by the policy.

**Comment by ywkim312** [comment]
This is not necessary, but if you want to connect it to incore-svc-data, this kind of yaml should work (not tested)
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: singleuser
  namespace: incore
spec:
  podSelector:
    matchLabels:
      app: jupyterhub
      component: singleuser-server
      release: jupyterhub
  policyTypes:
    - Egress
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              hub.jupyter.org/network-access-singleuser: "true"
      ports:
        - protocol: TCP
          port: notebook-port
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: incore-svc-data
      ports:
        - protocol: TCP
          port: 8888
    - to:
        podSelector:
          matchLabels:
            app=jupyterhub
            component=hub
            release=jupyterhub
      ports:
        - protocol: TCP
          port: 8081
    - to:
        podSelector:
          matchLabels:
            app=jupyterhub
            component=proxy
            release=jupyterhub
      ports:
        - protocol: TCP
          port: 8000
    - to:
        podSelector:
          matchLabels:
            app=jupyterhub
            component=autohttps
            release=jupyterhub
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8443
    - to:
        ipBlock:
          cidr: 169.254.169.254/32
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
    - to:
        ipBlock:
          cidr: 0.0.0.0/0
          except:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
            - 169.254.169.254/32
```
